_format_version: "3.0"
plugins:
- config:
    bandwidth_metrics: true
    latency_metrics: true
    per_consumer: true
    status_code_metrics: true
    upstream_health_metrics: true
  enabled: true
  name: prometheus
  protocols:
  - grpc
  - grpcs
  - http
  - https
